---
name: Data-FormValidator-Constraints-MethodsFactory
version: 0.01
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: Create constraints for Data::FormValidator
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::FormValidator: 4
build_requires:
  Test::More: 0
provides:
  Data::FormValidator::Constraints::MethodsFactory:
    file: lib/Data/FormValidator/Constraints/MethodsFactory.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
